FROM instrumentisto/flutter:3.41 AS build

WORKDIR /app
COPY pubspec.* ./
RUN flutter pub get

COPY . .
RUN flutter create --platforms=android --no-overwrite .

RUN flutter pub run easy_localization:generate -S assets/translations/
RUN flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart -S assets/translations/
RUN flutter build apk --release --no-tree-shake-icons

FROM scratch AS export

COPY --from=build /app/build/app/outputs/flutter-apk/app-release.apk /app-release.apk
