// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: const String.fromEnvironment("android_api_key"),
    appId: const String.fromEnvironment("android_app_id"),
    messagingSenderId: const String.fromEnvironment("messaging_sender_id"),
    projectId: const String.fromEnvironment("project_id"),
    storageBucket: const String.fromEnvironment("storage_bucket"),
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: const String.fromEnvironment("linux_api_key"),
    appId: const String.fromEnvironment("linux_app_id"),
    messagingSenderId: const String.fromEnvironment("messaging_sender_id"),
    projectId: const String.fromEnvironment("project_id"),
    authDomain: const String.fromEnvironment("auth_domain"),
    storageBucket: const String.fromEnvironment("storage_bucket"),
    measurementId: const String.fromEnvironment("linux_measurement_id"),
  );
}
